data:
  name: celeba
  type: image
  train_dir: data/celeba
  test_dir: data/celeba
  image_size: 64
  channels: 3
  n_labels: 40
network:
  class: pyrawavex
  kwargs:
    ds_size: 64
    n_filter: 24
    embed_size: 392
    lat_size: 392
    n_calls: 4
    shared_params: True
    adain: False
    dyncin: False
    letter_encoding: False
    perception_noise: False
    fire_rate: 1.0
z_dist:
  type: uniform
  z_dim: 196
training:
  out_dir: save/celeba_pyrawavex
  batch_size: 48
  batch_split: 4
  batch_mult_steps: 1
  n_workers: 2
  optimizer: adam
  lr: 0.0001
  equalize_lr: false
  n_epochs: 8
  save_every: 512
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  sample_every: 1
  sample_labels: 40
  d_reg_param: 10
  d_reg_every: 16
  g_reg_every: 0
  through_grads: True
  inception_every: 0
