data:
  name: celeba
  type: image
  train_dir: data/celeba
  test_dir: data/celeba
  image_size: 64
  channels: 3
  n_labels: 40
network:
  class: cell_ae_wavex_mix_wi
  kwargs:
    ds_size: 64
    n_filter: 24
    embed_size: 392
    lat_size: 392
    n_calls: 64
    shared_params: True
    adain: False
    dyncin: False
    letter_encoding: False
    perception_noise: True
    fire_rate: 1.0
    injected_encoder: True
z_dist:
  type: uniform
  z_dim: 196
training:
  out_dir: save/celeba_cell_ae_wavex_mix_wi
  persistence: True
  regeneration: True
  batch_size: 64
  batch_split: 2
  batch_mult_steps: 1
  n_workers: 2
  optimizer: adamp
  lr: 0.00005
  equalize_lr: false
  n_epochs: 32
  save_every: 256
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  sample_every: 1
  sample_labels: 40
  d_reg_param: 10
  d_reg_every: 16
  g_reg_every: 0
  through_grads: True
  inception_every: 0
