data:
  name: cifar10
  type: image
  train_dir: data/cifar10
  test_dir: data/cifar10
  image_size: 32
  channels: 3
  n_labels: 10
network:
  class: cell_ae_wavex_mix_gw
  kwargs:
    ds_size: 32
    n_filter: 64
    embed_size: 512
    lat_size: 512
    n_calls: 7
    shared_params: True
    gravity: True
    letter_encoding: False
    perception_noise: True
    fire_rate: 1.0
    injected_encoder: True
z_dist:
  type: uniform
  z_dim: 512
training:
  out_dir: save/cifar10_cell_ae_wavex_mix_gw_grav
  persistence: True
  regeneration: True
  batch_size: 64
  batch_split: 2
  batch_mult_steps: 1
  n_workers: 2
  optimizer: adam
  lr: 0.00001
  equalize_lr: false
  n_epochs: 1024
  save_every: 256
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  stream_every: 10
  sample_every: 1
  sample_labels: 10
  d_reg_param: 10
  d_reg_every: 16
  g_reg_every: 0
  through_grads: True
  inception_every: 0
