data:
  name: cifar10
  type: image
  train_dir: data/cifar10
  test_dir: data/cifar10
  image_size: 32
  channels: 3
  n_labels: 10
network:
  class: ca_manifold
  kwargs:
    ds_size: 32
    n_filter: 16
    lat_size: 512
    n_calls: 4
    shared_params: False
    letter_encoding: True
    perception_noise: True
    fire_rate: 1.0
training:
  out_dir: save/cifar10_ca_manifold_letenc_pnoise
  persistence: False
  regeneration: False
  batch_size: 64
  batch_split: 1
  batch_mult_steps: 4
  n_workers: 2
  optimizer: adamp
  lr: 0.0001
  equalize_lr: false
  n_epochs: 256
  save_every: 1
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  sample_every: 1
  sample_labels: 10