data:
  name: cifar10
  type: image
  train_dir: data/cifar10
  test_dir: data/cifar10
  image_size: 32
  channels: 3
  n_labels: 10
network:
  class: cell_ae
  kwargs:
    ds_size: 32
    n_filter: 32
    embed_size: 256
    lat_size: 3
    n_calls: 4
    shared_params: True
    adain: False
    dyncin: False
    letter_encoding: False
    perception_noise: False
    fire_rate: 0.5
z_dist:
  type: gauss
  z_dim: 3
training:
  out_dir: save/cifar10_cell_ae_sto_32_lat3
  batch_size: 64
  batch_split: 2
  batch_mult_steps: 1
  n_workers: 2
  optimizer: adamp
  lr: 0.0001
  equalize_lr: false
  n_epochs: 256
  save_every: 1
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  sample_every: 1
  sample_labels: 10
  d_reg_param: 10.
  d_reg_every: 4
  g_reg_every: 0
  through_grads: True
  inception_every: 0