data:
  name: emoji
  type: image
  train_dir: data/Emoji
  test_dir: data/Emoji
  image_size: 64
  channels: 4
  n_labels: 1
network:
  class: ca_manifold
  kwargs:
    ds_size: 64
    n_filter: 16
    lat_size: 512
    n_calls: 4
    shared_params: False
training:
  out_dir: save/emoji_ca_manifold
  batch_size: 64
  nworkers: 2
  optimizer: adam
  lr: 0.0001
  equalize_lr: false
  nepochs: 128
  save_every: 1
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  sample_every: 1
  sample_labels: 10