data:
  name: emoji
  type: image
  train_dir: data/emoji
  test_dir: data/emoji
  image_size: 32
  channels: 4
  n_labels: 9
network:
  class: cell_ae_wavex_mix_gw
  kwargs:
    ds_size: 32
    n_filter: 16
    embed_size: 256
    lat_size: 256
    n_calls: 7
    shared_params: True
    adain: False
    dyncin: False
    letter_encoding: False
    perception_noise: True
    fire_rate: 1.0
    injected_encoder: True
z_dist:
  type: uniform
  z_dim: 256
training:
  out_dir: save/emoji_s_cell_ae_wavex_mix_gw
  persistence: True
  regeneration: True
  batch_size: 64
  batch_split: 1
  batch_mult_steps: 1
  n_workers: 2
  optimizer: adam
  lr: 0.0001
  equalize_lr: false
  n_epochs: 8192
  save_every: 256
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  stream_every: 47
  sample_every: 16
  sample_labels: 9
  d_reg_param: 1
  d_reg_every: 16
  g_reg_every: 0
  through_grads: True
  inception_every: 0
