data:
  name: emoji
  type: image
  train_dir: data/emoji
  test_dir: data/emoji
  image_size: 32
  channels: 4
  n_labels: 9
network:
  class: cell_ae
  kwargs:
    ds_size: 32
    n_filter: 32
    embed_size: 256
    lat_size: 512
    n_calls: 4
    shared_params: True
    adain: False
    dyncin: False
    letter_encoding: False
    perception_noise: False
    fire_rate: 0.5
z_dist:
  type: gauss
  z_dim: 256
training:
  out_dir: save/emoji_s_cell_ae_sto_ntg
  persistence: False
  regeneration: False
  batch_size: 64
  batch_split: 2
  batch_mult_steps: 4
  n_workers: 2
  optimizer: adam
  lr: 0.0001
  equalize_lr: false
  n_epochs: 1024
  save_every: 1
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  sample_every: 16
  sample_labels: 9
  d_reg_param: 10.
  d_reg_every: 16
  g_reg_every: 16
  through_grads: False
  inception_every: 0