data:
  name: emoji
  type: image
  train_dir: data/emoji
  test_dir: data/emoji
  image_size: 64
  channels: 4
  n_labels: 9
network:
  class: ca_manifold
  kwargs:
    ds_size: 64
    n_filter: 16
    lat_size: 512
    n_calls: 4
    shared_params: False
    letter_encoding: True
    perception_noise: True
    fire_rate: 1.0
training:
  out_dir: save/emoji_ca_manifold_letenc_pnoise
  persistence: False
  regeneration: False
  batch_size: 64
  batch_split: 2
  batch_mult_steps: 4
  n_workers: 2
  optimizer: adam
  lr: 0.0001
  equalize_lr: false
  n_epochs: 8192
  save_every: 1
  lr_anneal: 1.0
  lr_anneal_every: 0
  monitoring: tensorboard
  sample_every: 16
  sample_labels: 9