data:
  name: emoji
  type: image
  train_dir: data/emoji
  test_dir: data/emoji
  image_size: 32
  channels: 4
  n_labels: 9
network:
  class: ca_manifold
  kwargs:
    ds_size: 32
    n_filter: 32
    embed_size: 256
    lat_size: 512
    n_calls: 4
    shared_params: False
    adain: False
    dyncin: False
    letter_encoding: False
    perception_noise: False
    fire_rate: 1.0
z_dist:
  type: gauss
  z_dim: 256
training:
  out_dir: save/emoji_s_ca_manifold_oc
  persistence: False
  regeneration: False
  batch_size: 256
  batch_split: 16
  batch_mult_steps: 1
  n_workers: 2
  optimizer: adam
  lr: 0.001
  equalize_lr: false
  n_epochs: 256
  save_every: 1
  lr_anneal: 1.0
  lr_anneal_every: 1
  monitoring: tensorboard
  sample_every: 16
  sample_labels: 9
  d_reg_param: 10.
  d_reg_every: 1
  g_reg_every: 0
  through_grads: True
  inception_every: 0